name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 8 * * 0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Conjur Install Script
      run: ./install.sh
